SKIN_FILE_PATH = "data\\skins.json"
SKIN_DATA_URL = "https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/skins.json"
CHAMPION_FILE_PATH = "data\\champions.json"
CHAMPION_DATA_URL = "https://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/v1/champion-summary.json"
RAW_DATA_PATH = "data\\raw"
EXPORT_PATH = "export"
TEMPLATE_PATH = "templates"
FAILED_ACCOUNT_PATH = "failedAccounts.txt" # in export folder
UNFINISHED_ACCOUNT_PATH = "uncheckedAccounts.txt"
RIOT_CLIENT_LAUNCH_COOLDOWN = 5
RIOT_CLIENT_LOADING_RETRY_COOLDOWN = 5
LEAGUE_CLIENT_LAUNCH_COOLDOWN = 5
LAUNCH_COOLDOWN_ON_INVALID_CREDENTIALS = 30
RATE_LIMITED_COOLDOWN = 300
MAX_RATE_LIMITED_ATTEMPTS = 5
MAX_FAILED_ATTEMPTS = 5